name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  pi_server:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    - name: install dependencies and run tests
      run: |
        pip install pi_server/.[dev]
        python -u -m pytest -vv pi_server

  webapp:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: install dependencies and run tests
      run: |
        pip install webapp/.[dev]
        python -u -m pytest -vv webapp
